# Generated by Django 3.2.9 on 2021-12-21 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_parqueo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 11, 54, 21, 453070)),
        ),
    ]
