# Generated by Django 3.2.9 on 2021-12-21 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_parqueo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleparqueo',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 19, 39, 11, 555036)),
        ),
        migrations.AlterField(
            model_name='parqueo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 19, 39, 11, 554040)),
        ),
    ]
