# Generated by Django 3.2.9 on 2021-12-22 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20211221_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleparqueo',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 20, 55, 16, 358316)),
        ),
        migrations.AlterField(
            model_name='parqueo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 20, 55, 16, 358316)),
        ),
    ]
