# Generated by Django 3.2.9 on 2021-12-23 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20211221_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleparqueo',
            name='fecha_entrada',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 20, 4, 1, 400107)),
        ),
        migrations.AlterField(
            model_name='parqueo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 20, 4, 1, 399134)),
        ),
    ]
